### ISSUE TITLE
Change all used icons to Font Awesome

### ISSUE THREAD

**Issue by welcomehelp** [welcomehelpde/engelsystem#1]
Better usage and readability, fewer compatibility problems, fa.css already integrated in layout.html
http://fontawesome.io/icons/
Examples: <i class="fa fa-hand-peace-o"></i>
![fireshot screen capture 249 - treffen - welcome help engelsystem - sunyque_de__p user_meetings](https://cloud.githubusercontent.com/assets/15015628/10355930/bd4dae3a-6d71-11e5-94a4-f652ea855929.png)

**Comment by sdvg** [comment]
Es sind jetzt nur noch die Länder-Flaggen für die Sprachauswahl und die Emoticons übrig (beide nicht in FontAwesome enthalten). Icomoon ist raus geflogen.
