### ISSUE TITLE
"Ersthelfer-Info" per E-Mail nach Signup (mit pdf-Anhang)

### ISSUE THREAD

**Issue by welcomehelp** [welcomehelpde/engelsystem#12]
Send a standard-mail with pdf-attachement (easy to exchange/edit) to newly signed up members automatically.

**Comment by netrunner99** [comment]
Wenn, dann PDF Inhalt mit als plain text redundant in der eMail auch mitschicken. PDF allein als Mailanhang liest niemand!!

**Comment by netrunner99** [comment]
Umsetzung erst ohne PDF

**Comment by avahldiek** [comment]
Hi, should find time to implement tonight. Few questions:
- would you like to have the text sent with the verification or in a separate email after successful verification.
- who should be able to edit the text?
-do you have a suggestion for where to add the text field to edit?

**Comment by netrunner99** [comment]
hi avahldiek! :) it should only be a static text .. nobody should edit the text.

it is really a question, if the text content should be maintained within the system. not necessarily indeed. .. and PDF would just be a nice to have feature for printing reasons .. not a hard requirement.

**Comment by sdvg** [comment]
The system only uses gettext to manage text-content. I would leave it at that, for the moment.

I would send the info-mail after the user verified himself successfully. Otherwise the mail could be misleading or distract from the verification-link.

**Comment by avahldiek** [comment]
Sorry for pushing it into the same pull request (https://github.com/welcomehelpde/engelsystem/pull/31), got mixed up. I think there is value in not using gettext and instead read from a text file (this file can easily be modified and may contain multiple languages). We may not have all the locals available. The text of course is currently very basic and should be updated.

**Comment by welcomehelp** [comment]
Would be very helpful to have a solution like you've described, avahldiek!
It can be neccessary to change the "welcome text" from time to time, so a separate textfile to include in the e-mail as plain text is great!

**Comment by sdvg** [comment]
Dateipfad sollte konfigurierbar sein.
