### ISSUE TITLE
Erweiterung der User-Profile um einige Felder

### ISSUE THREAD

**Issue by welcomehelp** [welcomehelpde/engelsystem#14]
Ja Nein Feld Engel hat Führerschein Kl B
Ja Nein Feld Engel hat KFZ
Ja Nein Feld Engel hatte bereits eine Einweisung oder nicht
2 Feld Engel hat Erfahrung als/in  ....
Feld Engel hat Erfahrung als/in Fahrer
Feld Engel hat Erfahrung als/in Kleiderkammer

**Comment by sdvg** [comment]
Ich würde das gerne übernehmen, dann aber direkt richtig mit den Profilfeldern aufräumen.

Die Felder wären dann also:

(Bestehende Felder)
* Benutzername
* Nachname
* Vorname
* Geplanter Beginn der Verfügbarkeit
* Geplantes Ende der Verfügbarkeit
* Alter
* Geschlecht
* Telefon
* Handy
* E-Mail
* Jabber (kann raus?)
* Weitere Qualifikationen (da würde ich nur die Beschreibung ändern wenn wir z.B. Führerschein in eigenem Feld abfragen)
* Aussehen (... der Seite; wird das wirklich gebraucht?)
* Sprache (würde hier eine Mehrfachauswahl / -eingabe Sinn machen?)
(Neue Felder)
* Helfer-Status (siehe #18)

**Comment by sdvg** [comment]
Ich würde das gerne übernehmen, dann aber direkt richtig mit den Profilfeldern aufräumen.

Die Felder wären dann also:

(Bestehende Felder)
* Benutzername
* Nachname
* Vorname
* Geplanter Beginn der Verfügbarkeit
* Geplantes Ende der Verfügbarkeit
* Alter
* Geschlecht
* Telefon
* Handy
* E-Mail
* Jabber (kann raus?)
* Weitere Qualifikationen (da würde ich nur die Beschreibung ändern wenn wir z.B. Führerschein in eigenem Feld abfragen)
* Aussehen (... der Seite; wird das wirklich gebraucht?)
* Sprache (würde hier vielleicht eine Mehrfachauswahl / -eingabe Sinn machen?)

(Neue Felder)
* Checkbox _Führerschein Klasse B_
* Checkbox _Hat eigenes KFZ_
* Checkbox _Hat Erfahrung als Fahrer_
* Checkbox _Ist eingewiesen_ (siehe auch #18)
* Checkbox _Hat Erfahrung in Kleiderkammer_
* Textfeld(er) _Erfahrung_ (Verstehe nicht ganz, warum das zwei Felder sein sollen. Würde hier nicht ein freies Textfeld, wo man beliebig viele "Erfahrungen" rein schreiben kann besser passen? Oder man macht es komplett als Checkboxen / Mehrfachauswahl mit vorgegebenen Werten.)

a) Kann von den oben genannten Felder irgendetwas raus oder sollte geändert werden?
b) Sollen alle Felder direkt bei der Registrierung abgefragt oder sich zum Teil erst später im Profil bearbeiten lassen?

Schon mal Danke für mehr Infos :)

**Comment by netrunner99** [comment]
Es würde den Aufbau einer Kataloghierachie notwendig machen. Simplicity prefered.
