### ISSUE TITLE
RedirectLoop

### ISSUE THREAD

**Issue by zhksh** [welcomehelpde/engelsystem#26]
install.sql aus repo wurde verwendet

Beim ersten Login als Admin tritt p == 'user_shifts' ein 
index.php 93 content = user_shifts 
user_shifts.php z.326 user_shifts() -> view_user_shifts() 
z.342 view_user_shifts() findet keine einträge -> redirect('?') 
index.php z.32  isset($user) == true dann p = 'shifts'
index.php z.71 list($title, $content) = shifts_controller()
shifts_controler.php z.62 kein 'action' parameter dann redirect('user_shifts') 

ich kenne das system noch zu schlecht um das in vernünftiger zeit selber zu fixen
vielleicht schickt mir jemand seine datenbank mit shift einträgen damit ich ohne viel raten an was arbeiten kann

**Comment by avahldiek** [comment]
Hi
hatte das problem auch. Bei mir fuehrte das Fehlen eines Shift eintrages in der Datenbank dazu, dass in user_shifts.php:335 if (count($rooms) == 0) {
    error(_("The administration has not configured any locations yet."));
    redirect('?');
  }

Immer und immer wieder ausgefuehrte wurde. Denn in index.php29 wird man immer wieder auf shifts weitergeletet, wenn man angemeldet ist, aber kein p parameter gesetzt wurde.

Loesung bei mir, war deshalb. Kurzerhand Zeilen 29-30 in public/index.php zu kommentieren, dann sollte der Login dich erstmal reinlassen. 
Danach habe ich dann ueber das Interface erst einen Raum (p=admin_room) und dann eine Schicht(p=admin_shifts) hinzugefuegt.

Danach einfach wieder das Kommentar in index.php entfernen und alles sollte funktionieren. Ueberlege gerade, wie man das am Besten fixed. Bin fuer Vorschlaege offen.

Wuerde diesen Thread gerne auch dazu benutzen darauf hinzuweisen, dass die bootstrap Bibliotheken fehlen bzw. die Softlinks in Verzeichnisse ausserhalb vom repository. Dadurch funktionieten bei mir die Menue's am Anfang auch nicht. Muesste zur Installationsanleitung hinzugefuegt werden, damit man weiss, dass diese Links noch an das System anzupassen sind.

**Comment by rantansplan** [comment]
zunächst als workaround eine install.sql mit dummyeintrag
dann aber auf jeden fall einen fix, das system liegt ja sonst komplett lahm

**Comment by welcomehelp** [comment]
Ja, wir haben die "Startseite" nach Login auf shifts view verbogen, damit die User nicht erst über das Menü da hin kommen. Leider ist bei einem frischen Engelsystem noch kein Helfertyp, Ort und Schicht angelegt, wodurch dann der Loop entsteht und es notwendig ist, diese Punkte erst anzulegen.
install.sql mit Dummy-Eintrag finde ich gar nicht schlecht, so ist bei einer neuen Installation quasi gleich ein "Beispiel" im System.

**Comment by avahldiek** [comment]
OK, kann heute Abend das install.sql aendern...

Wie habt ihr das fuer die Zukunft mit den bootstrap Referenzen geplant?

**Comment by rantansplan** [comment]
es gibt auch noch ein paar bugs in der update.php , ich werde einen pull 
request mit meiner aktuellen install.sql und ein paar korrekturen an der 
update.php stellen

Am 22.10.2015 um 17:13 schrieb Welcome Help!:

**Comment by welcomehelp** [comment]
Super, danke!

**Comment by ynux** [comment]
Hi, wegen der bootstrap links: Der Plan ist, die Pfade im Code so zu korrigieren, dass die Links nicht mehr gebraucht werden. Gibt es für diesen Job Freiwillige?

**Comment by rantansplan** [comment]
ja mach ich noch und requeste morgen den pull

Am 22.10.2015 um 19:49 schrieb ynux:

**Comment by rantansplan** [comment]
es gibt auch zwei vendor verzeichnisse, warum ?

Am 22.10.2015 um 19:49 schrieb ynux:

**Comment by ynux** [comment]
Um Verwirrung zu stiften. Das klappt ganz gut. Im Ernst, das sollte auch in Ordnung gebracht werden. Ich weiss aber nicht, ob es einen Styleguide zum Filetree gibt.

**Comment by EtherNett** [comment]
wirklich klasse was Ihr grad macht - ich komme gar nicht mit lesen nach...
hilfe hol zum reviewen +1000thnx - grade die links haben mich etwas Zeit gekostet zu kapiern das es immer anders commtite wird mit full paths ...    daumen hoch
