### ISSUE TITLE
"Verifizierungsmail erneut senden"-Funktion, im Registrierungsprozeß UND in der Admin-View

### ISSUE THREAD

**Issue by netrunner99** [welcomehelpde/engelsystem#41]
1) Erstellen einer "Verifizierungsmail erneut senden" Seite um einen neuen mail-verification-token zu erzeugen und per eMail zu versenden.

2) diese Funktion soll als Button sowohl auf der Registrierungsseite als auch über die Admin-View der Nutzerseite erreichbar sein.

**Comment by sdvg** [comment]
> 2) diese Funktion soll als Button sowohl auf der Registrierungsseite [...]

Ich würde den gerne direkt in die Fehlermeldung ("Du bist noch nicht verifiziert...") beim Login einbauen. Was meinst du dazu?

**Comment by netrunner99** [comment]
gute idee! dann dort auch! sprich: an mindestens diesen 3 stellen.

**Comment by avahldiek** [comment]
Koennte es heute abend machen. 2) (User Ansicht als Admin) und 3) (nach fehlgeschlagenem Loginversuch) verstehe ich. Koenntet ihr nochmal beschreiben wie der use case fuer 1) aussieht. Wenn der User eine neue eMail nach dem fehlgeschlagenen Login und der Admin ueber die Userseite erzeugen kann, dann sehe ich keinen weiteren use case.
Danke fuer die Klaerung. Wuerde erstmal 2) und 3) implementieren, wenn dann noch bedarf an 1) ist, sagt bescheid.

**Comment by sdvg** [comment]
(WIP Label für avahldiek gesetzt, danke schon mal!)

**Comment by avahldiek** [comment]
Ich denke, ich verstehe nun, was du mit einer eigenen Seite zum nochmaligen senden des Verifiizierungstoken meintest. Diese sollte wahrscheinlich der Passwortvergessen Seite ahnlich sein. Ist das soweit richtig?

In der bisherigen implementierung ist es so, dass der User selbst nur den Link zum erneuten Senden des Verifizierungslinks bekommt, wenn dieser ein Loginversuch macht. Wird dieser Versuch nicht unternommen, hat der User keine Idee, wie die Situation zu loesen ist. Deshalb waere ein Button unter dem Passwortvergessen Button wahrscheinlich garnicht so schlecht. Netrunner99 ware dies eine Loesung fuer 1)?

**Comment by EtherNett** [comment]
jepp - makes sense - do this please

**Comment by avahldiek** [comment]
done

**Comment by netrunner99** [comment]
sorry .. das war jetzt leider nicht abgesprochen .. button bitte auf die registrierungseite .. nicht unter passwort vergessen.

**Comment by EtherNett** [comment]
Warning: Illegal string offset 'UID' in includes/controller/users_controller.php on line 35 im Adminbereich beim manuellen Neu Versenden für einen Benutzer aufgetreten

**Comment by EtherNett** [comment]
resend token, start password recovery works, from loginpage and inside - (a admin can also resend for the user from the login)
