### ISSUE TITLE
Verifzierungsmail kommt bei GMAIL und GMX nicht an.

### ISSUE THREAD

**Issue by netrunner99** [welcomehelpde/engelsystem#42]
Aus bisher ungeklärten Ursachen kommen bei Google Mail und GMX (teils oder alle?) die Verifizierungsmail nicht an. Es können mehrere Gründe dafür vorliegen.

**Comment by ynux** [comment]
Bei mir gibt es dazu lokale mails mit Hinweisen zu den Ursachen, Subject: Undelivered Mail Returned to Sender.

**Comment by netrunner99** [comment]
bei GMX ist es geklärt: mit delay im spam gelandet. GMX hat sporadisch auch sehr lange, unvorhersagbare delays.

**Comment by sdvg** [comment]
Im Spam sollte die Mail ja eigentlich nicht landen. Kann man bei GMX die Mailheader auslesen und steht da vielleicht der Grund drin?

**Comment by netrunner99** [comment]
einer der gmail-user schreibt:

"lese gerade, daß ihr dem "Problem mit den Bestätigungsmail" nachgeht.  Dazu:... mein ipone hat mich vorhin darauf aufmerksam gemacht ich solle meine Einstellungen prüfen, da ich "... mails"  nicht empfangen kann.  
Hab eine Sperre : e-mail empfangen von - icloud -  dringehabt,.. Vielleicht liegt es daran??"

kennt sich jemand mit icloud und mailempfang aus?

**Comment by netrunner99** [comment]
es lag an der email konfiguration von php .. erledigt.
