### ISSUE TITLE
Pflichtfelder von Registrierung sind keine Pflichtfelder in Profil bearbeiten

### ISSUE THREAD

**Issue by EisenRatte** [welcomehelpde/engelsystem#44]
Pflichtfelder von Registrierung sind keine Pflichtfelder in Profil bearbeiten und können daher dort wieder geleert werden.

**Comment by netrunner99** [comment]
Im Grunde diegleiche Bug wie #46 soll zusammen begearbeitet werden!

**Comment by zhksh** [comment]
mach ich

**Comment by zhksh** [comment]
ich glaube man muss den titel von diesem issue ändern, es sind genau die pfilchtfelder aus der register auch die pflichtfelder in der user_settings. nur die auszeichnung stimmt in beiden nicht. vorname und nachname sind als pflicht ausgezeichnet werden aber nicht validiert.

**Comment by zhksh** [comment]
die frage ist was soll pflicht sein

**Comment by netrunner99** [comment]
ja, für das aktuelle system soll auch die vorname und nachname zumindest in der eingabe geprüft sein. eine identitätsvalidierung ist es noch nicht. (das könnte uns sogar auch noch blühen.)
