### ISSUE TITLE
Make Engelsystem customizable

### ISSUE THREAD

**Issue by welcomehelp** [welcomehelpde/engelsystem#45]
- Dinge wie der Name im Menü (layout.html), das Logo auf dem Dashboard, der Footer, die Seiten "Impressum" und "Datenschutz", wie auch viele andere Textbausteine müssen einfach zu ändern sein, sollten wir das Engelsystem für einen neuen Standort verfügbar machen.
- Am Besten wäre wohl eine Struktur mit Variablen/Platzhaltern, die über eine zentrale Config-Datei editierbar sind.
- Unser "Master" bei github sollte zukünftig frei von standortspezifischen Änderungen sein (dies sollte wie oben genannt einfach über eine config anpassbar sein)

**Comment by TheJumper** [comment]
# Suggestion

The Model-View-Controller design pattern is already kinda in place, although it only uses functions. My suggestion is: we should keep and extend this structure. Components should be isolated as much as possible and OOP should always be the way to go. (For the sceptics: PHP OOP got a whole lot more mature than it used to be and with PHP 7 on the horizon it's safely the way to go.)

![MVC](https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/ModelViewControllerDiagram.svg/800px-ModelViewControllerDiagram.svg.png)

* **Model:** Manages the data. All data processing that is associated to this component should be done within the scope of this class.
* **View:** HTML template with templating engine. Renders output that is generated by the interaction of the two other components. A base template should outline the general layout and organize it in blocks. Templates down the inheritance tree should always overwrite or extend the given blocks. Customer specific extensions would just overwrite or extend the needed blocks.
* **Controller:** By registering itself in the routing, the controller processes the request, applies the model and finally delegates the View drawing. 

Editable configs should be wrapped into a model, system configs couldbe done within configuration files.

**Comment by sdvg** [comment]
* URL auf der Startseite sollten auch relativ sein, keine absolute URLs zu Produktivsystemen
* Google Analytics Code sollte konfigurierbar und optional sein

**Comment by EtherNett** [comment]
only some links in the footer is static left now. - customizing etc config files makes it more easy now. we can close this in the near beginning of the rewrite of the engelsystem. @TheJumper you are also welcome to work with us on the new rewrite - we are starting at next week  by a hangout - and we meet in münchen also - just ask me if you are interested. lots of todo now !
