### ISSUE TITLE
rollenbasierte View für die Helferliste 

### ISSUE THREAD

**Issue by netrunner99** [welcomehelpde/engelsystem#47]
Die Helferliste in der Ansicht für die Rolle "Leiter" MUSS Name, Vorname und Mailadresse enthalten, da Meldelisten damit erstellt werden sollen. Hier reicht eine anonyme Ansicht NICHT aus!

Dagegen sollen die Klarnamen der Helfer in der Schichtleiteransicht und in der Helferansicht NICHT sicherbar sein.

**Comment by sdvg** [comment]
Sollen Klarnamen auch schon für "4-Teamleitung" oder erst ab "5-Leitung" angezeigt werden?

**Comment by netrunner99** [comment]
(vorerst) nur für ab "5-leitung"

es ist trotzdem eine unbequemlichkeit für die schichtleiter/teamleitung nach benutzernamen die helfer zu identifizieren .. aber bisher keine beschwerde drüber.

nur der leiter soll personallisten erstellen können. da müssen alle real life angaben drauf .. aktiv oder nicht aktiv wäre dagegen egal ... vielleicht können wir das mit den verschiedenen helferlisten lösen .. jede rolle kriegt eine andere view zu sehen und gut. .. wir haben bisher 3 verschiedene helferlisten in der adminkonsole .. und davon ist nicht jede gut nutzbar ... das ist zu optimieren.

**Comment by sdvg** [comment]
Ich habe ein neues Privileg `access_userdata` angelegt, mit dem man generell steuern kann, ob eine Benutzergruppe diese Daten sehen darf oder nicht. Das Privileg an sich kommt mit dem Update, die Konfiguration der Benutzergruppen muss noch manuell ausgeführt werden (/?p=admin_groups).

**Comment by EtherNett** [comment]
Ja Hervorragend strukturierte Lösung - da das an versch Standorten verschieden benötigt wird !
lokale Gruppen cfg ist customizing thnx
