### ISSUE TITLE
Current templating system is a mess

### ISSUE THREAD

**Issue by TheJumper** [welcomehelpde/engelsystem#49]
The current templating system is based on loosly coupled and used functions that dont provide the security and the level of abstractation that would be sufficient for the project and especially for the fulfillment of #45.

**Comment by netrunner99** [comment]
haha .. issue widely known .. BUT .. is it easy to clean up? .. any concept? .. it would be a medium term task, imho

**Comment by TheJumper** [comment]
Switch it out for sth like smarty or twig. Clean blocks and inheritance features could help to make the system more modular and configureable.

**Comment by sdvg** [comment]
IMO we can't do this for the current system with a reasonable effort.
