### ISSUE TITLE
Eingeloggten User von Login-Seite sofort weiterleiten

### ISSUE THREAD

**Issue by EisenRatte** [welcomehelpde/engelsystem#53]
Wenn ein eingeloggter User auf die Login-Seite navigiert sollt er/sie sofort auf das Dashboard/die nächste Seite im Workflow weitergeleitet werden

**Comment by netrunner99** [comment]
welche seite ist mit der "nächsten seite im workflow" gemeint?

**Comment by netrunner99** [comment]
jetzt wird nach dem login der aktuelle schichtplan angezeigt. ist es nicht der nächste schritt im workflow? wenn nicht, bitte spezifizieren.

**Comment by EisenRatte** [comment]
Ja, momentan ist das der Schichtplan. Also bitte einen  eingeloggten User der auf die Login-Seite navigiert sofort auf den Schichtplan weiterleiten.

**Comment by netrunner99** [comment]
versteh die anfrage nicht, es ist bereits der IST-zustand

**Comment by EisenRatte** [comment]
nein, wenn ein EINGELOGGTER user auf die Login Seite kommt wird er nicht automatisch weitergeleitet.

**Comment by netrunner99** [comment]
ja, stimmt. das sollte nicht sein .. aber nach normaler benutzerführung kommt man gar nicht dahin. außer man geht manuell in die URL eingabe in der adressleiste des browsers .. das sollte durchaus geändert werden.

**Comment by zhksh** [comment]
see <a href = "https://github.com/welcomehelpde/engelsystem/pull/56">#56</a>
