### ISSUE TITLE
Show Klarnamen in Dialogs ( eg. add user to shift if a user does not itself.) 

### ISSUE THREAD

**Issue by EtherNett** [welcomehelpde/engelsystem#86]
as in #77 but all dialoges to check. 

all of this should be: - 
System works in Klarnamen  > show it in any listing and "Auswahlfeld"   if the Right to see it is given.
System works in aliasnames > work in any listing with alias names.

**Comment by EtherNett** [comment]
anyway the shiftleaders should have one list with alias and Klarnamen - new issue or not...
eg. double the All Users List - and take the gender field to show the nicks

**Comment by Grreg** [comment]
Für Issue86
https://github.com/welcomehelpde/engelsystem/pull/95
Testbar: http://gruszka.online/engl_iss86/
