### ISSUE TITLE
List of who is

### ISSUE THREAD

**Issue by EtherNett** [welcomehelpde/engelsystem#87]
to be able to filter /  see who ist admin - who is this and that ...in which group. of rights.

**Comment by Grreg** [comment]
Started working on this ...

**Comment by Grreg** [comment]
https://github.com/welcomehelpde/engelsystem/pull/92
commited as root on localhost ... shame on me! -.-

**Comment by Grreg** [comment]
https://github.com/welcomehelpde/engelsystem/pull/93  This should finally do it :)

**Comment by EtherNett** [comment]
it does ! - to be more tested cause i got long waits at searching more than one searches in Browser  - i will recheck if this can be reproduced  - or just a fail at testing

**Comment by Grreg** [comment]
Für Issue87
https://github.com/welcomehelpde/engelsystem/pull/94
Testbar: http://gruszka.online/engl_iss87/

**Comment by Grreg** [comment]
I cannot reproduce your performance issue. The list is loading superfast. I know that old Internet Explorers (<=8) are sometimes pretty slow in rendering long tables, but cannot imagine it is what u describe. Please give me more detailed information about what u tested and what the result was.
