### ISSUE TITLE
"telefonliste cvs export" Sort Filter & button to the Helferliste

### ISSUE THREAD

**Issue by EtherNett** [welcomehelpde/engelsystem#97]
- In der Helferliste (und den anderen Listen) ist es nicht praktikabel nach Alias, Vorname, Nachname zu sortieren. Ein Formatierter Druck als pdf ist nicht implementiert, ein copy paste ist nicht praktikabel, das habe ich extra ausprobiert. Also ist ein csv export am schnellsten geeignet - in einer excel Listan kann man sortieren, filtern, den druck Formatieren. Wird in den Helferorganisationen dringend benötigt zum Benachrichtigen - für Helfer die das Anrufen übernehmen, aber z.B nicht Schichtleiterstatus haben, also die Daten / Listen im System gar nicht sehen  können. Auch für die Vereinsarbeit.
Liste: NachN, VorN, NickN, Tel, Mobil, Mail. Skills     > button to export csv ( check the csv Format -ich habe z.B falsche Umlautübersetzungen bekommen beim export aus der DB )

**Comment by avahldiek** [comment]
Bisherige umsetztung ist ein schneller hack und gibt eine csv liste raus. Zugriff haben nur admins.

ich war mir nicht sicher, was du genau mit skills meinst. Sind das die Angeltypes in denen der user eingetragen ist? (deshalb sind sie erstmal nicht dabei)

**Comment by EtherNett** [comment]
im Text schreiben die user "skills" rein wie Führerschein Sprachen etc..., ja aber natürlich wäre eine erweiterte Ausgabe mit den Helfertypen auch gut - alles was die Planung unterstützt.

**Comment by avahldiek** [comment]
done...

Komma im Kommentartext sind kein Problem.

**Comment by sdvg** [comment]
Ich habe über den PR #99 noch etwas geändert.
Getestet werden kann jetzt hier: http://gruszka.online/engl_pr99/

In Excel öffnet man den Export übrigens am besten, indem man die Import-Funktion nutzt und als File origin Unicode (UTF-8) auswählt.

![text import wizard - step 1 of 3 2015-12-12 15-14-56](https://cloud.githubusercontent.com/assets/971072/11762327/1f886636-a0e3-11e5-8ee1-6bfbf219d4aa.png)

**Comment by EtherNett** [comment]
import am MAC unter Libre Office höher 4.3 klappt sofort - utf-8 ist sofort erkannt und problemlos.
bei Excel 2011 (14.5.4) probleme mit Umlauten egal was ich auch Einstelle. gibt es die Möglichkeit den Export hier schon abzusichern vor diesen "codepage" Fehlern ?

**Comment by sdvg** [comment]
Ja, die (alte) 2011er Version für Mac unterstützt noch kein UTF-8. Müssen wir die unterstützen? Bei der aktuellen Version und auf Windows sollte die Darstellung fehlerfrei sein.

**Comment by EtherNett** [comment]
Nein - dann alles bestens - dann reicht es mir zu wissen, das es auf kostenlosem Openoffice und Libre Office funkt - und MS Office 2011 am Mac "Alt" ist.

**Comment by sdvg** [comment]
Danke für's Testen, ist gemerged.
